# Generated by Django 2.2.3 on 2019-08-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamento', '0002_iniciativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='diputado',
            name='slug',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
